version: '3.9'

services:
  client:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_BASE_API_URL=http://localhost:8080
    restart: unless-stopped
    depends_on:
      - server

  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
      - JWT_SECRET=YOUR_SUPER_SECURE_JWT_SECRET
      - COOKIE_PATH=/
      - PORT=8080
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}
